// Centralized candidate data - Single source of truth
export const candidateData = {
  name: 'Thapelo Moalosi',
  title: 'Junior Cybersecurity Analyst',
  location: 'Katlehong, Gauteng, South Africa',
  email: 'p3llowb33@gmail.com',
  phone: '071 897 9396',
  github: 'https://github.com/P3llowb33',
  linkedin: 'https://www.linkedin.com/in/thapelo-moalosi-469b84204/',
  coreAreas: [
    'Defensive Security',
    'Network Security',
    'Security Monitoring',
    'Threat Detection',
    'SOC Fundamentals',
    'Security Analysis',
    'Networking',
  ],
  tagline: 'Building practical foundations in networking, defensive security, security monitoring and threat detection while developing toward a career in cybersecurity.',
};

export const experience = [
  {
    id: 'truworths',
    company: 'Truworths',
    location: 'Benoni, Gauteng',
    position: 'Sales Consultant',
    subtitle: 'Progressed from Sales Learnership',
    startDate: 'July 2025',
    endDate: 'Present',
    responsibilities: [
      'Customer service',
      'Sales support',
      'POS transactions',
      'Cash handling',
      'Banking procedures',
      'Stock management',
      'Replenishment',
      'Merchandising',
      'Fraud prevention awareness',
      'Loss prevention',
      'POPI awareness',
      'Customer-service procedures',
      'Product training',
      'Teamwork',
    ],
    transferableStrengths: [
      'Attention to detail',
      'Accuracy',
      'Responsibility',
      'Following procedures',
      'Problem solving',
      'Communication',
      'Adaptability',
      'Reliability',
      'Teamwork',
    ],
    disclaimer: 'This role is retail experience. The transferable skills are presented because they support the transition into cybersecurity.',
  },
  {
    id: 'topsellers',
    company: 'Topsellers',
    location: 'Katlehong, Gauteng',
    position: 'Salesperson',
    startDate: 'September 2022',
    endDate: 'February 2023',
    responsibilities: [
      'Sales support',
      'Customer engagement',
      'Product knowledge',
      'Transaction processing',
    ],
  },
];

export const education = [
  {
    id: 'katlehong-tech',
    type: 'completed',
    institution: 'Katlehong Technical High School',
    qualification: 'National Senior Certificate (Grade 12)',
    startDate: '2018',
    endDate: '2020',
  },
];

export const previousStudies = [
  {
    id: 'nmu-bit',
    institution: 'Nelson Mandela University',
    qualification: 'Bachelor of Information Technology (BIT)',
    status: 'NOT COMPLETED',
    note: 'Studied toward the qualification but did not complete it. This foundation contributed to an interest in technology and computing.',
  },
];

export const training = [
  {
    id: 'cisco-cybersecurity',
    category: 'Cybersecurity / Technology Training',
    provider: 'Cisco Networking Academy',
    course: 'Introduction to Cybersecurity',
    startDate: '2023',
    endDate: '2026',
    status: 'CURRENT',
    type: 'training',
  },
  {
    id: 'cisco-iot',
    category: 'Cybersecurity / Technology Training',
    provider: 'Cisco Networking Academy',
    course: 'Introduction to Internet of Things (IoT)',
    startDate: '2023',
    endDate: '2023',
    status: 'COMPLETED',
    type: 'training',
  },
  {
    id: 'capaciti-ai',
    category: 'Current Development',
    provider: 'CAPACITI',
    course: 'AI Development Programme',
    status: 'CURRENT',
    note: '1-week programme. Current technology development - not presented as a cybersecurity certification.',
    type: 'training',
  },
  {
    id: 'customer-service',
    category: 'Professional & Compliance Training',
    provider: 'Truworths',
    course: 'Customer Service Training',
    status: 'COMPLETED',
    type: 'training',
  },
  {
    id: 'fraud-prevention',
    category: 'Professional & Compliance Training',
    provider: 'Truworths',
    course: 'Fraud Prevention / Fraud Heroes Training',
    status: 'COMPLETED',
    type: 'training',
  },
  {
    id: 'popi-training',
    category: 'Professional & Compliance Training',
    provider: 'Truworths',
    course: 'POPI Training',
    status: 'COMPLETED',
    type: 'training',
  },
  {
    id: 'product-training',
    category: 'Professional & Compliance Training',
    provider: 'Truworths',
    course: 'Product Training',
    status: 'COMPLETED',
    type: 'training',
  },
  {
    id: 'sales-operations',
    category: 'Professional & Compliance Training',
    provider: 'Truworths',
    course: 'Sales & Retail Operations Training',
    status: 'COMPLETED',
    type: 'training',
  },
];

export const skills = {
  networking: [
    {
      id: 'network-fundamentals',
      name: 'Networking Fundamentals',
      status: 'DEVELOPING',
      description: 'Understanding of network protocols, infrastructure, and communication models.',
      relatedTraining: ['cisco-cybersecurity', 'cisco-iot'],
    },
    {
      id: 'cisco-networking',
      name: 'Cisco Networking',
      status: 'DEVELOPING',
      description: 'Cisco networking concepts and tools.',
      relatedTraining: ['cisco-cybersecurity', 'cisco-iot'],
    },
  ],
  cybersecurity: [
    {
      id: 'cybersecurity-fundamentals',
      name: 'Cybersecurity Fundamentals',
      status: 'LEARNING',
      description: 'Core concepts of defensive security, threat models, and security principles.',
      relatedTraining: ['cisco-cybersecurity'],
    },
    {
      id: 'data-security',
      name: 'Data & Information Security',
      status: 'LEARNING',
      description: 'Understanding data protection, classification, and handling.',
      relatedTraining: ['cisco-cybersecurity'],
    },
  ],
  systems: [
    {
      id: 'computer-literacy',
      name: 'Computer Literacy',
      status: 'PRACTICAL',
      description: 'General computer operations, troubleshooting, and system management.',
    },
    {
      id: 'it-troubleshooting',
      name: 'IT Troubleshooting',
      status: 'DEVELOPING',
      description: 'Diagnostic and problem-solving approaches for technical issues.',
    },
  ],
  monitoring: [
    {
      id: 'security-monitoring',
      name: 'Security Monitoring Concepts',
      status: 'LEARNING',
      description: 'Understanding SIEM concepts, log analysis, and alert investigation.',
      relatedProject: 'soc-monitoring',
    },
  ],
  tools: [
    {
      id: 'cisco-packet-tracer',
      name: 'Cisco Packet Tracer',
      status: 'EXPOSURE',
      description: 'Network simulation and design tool.',
      relatedTraining: ['cisco-cybersecurity'],
      relatedProject: 'network-security',
    },
  ],
  futureAreas: [
    { name: 'Python', focus: 'Security automation and scripting' },
    { name: 'PowerShell', focus: 'Windows system administration' },
    { name: 'Bash', focus: 'Linux system administration' },
    { name: 'Linux', focus: 'Security operations' },
    { name: 'Wireshark', focus: 'Network packet analysis' },
    { name: 'Nmap', focus: 'Network reconnaissance' },
    { name: 'SIEM', focus: 'Security information and event management' },
    { name: 'Splunk', focus: 'Log analysis and monitoring' },
    { name: 'Microsoft Sentinel', focus: 'Cloud security monitoring' },
    { name: 'Active Directory', focus: 'Identity and access management' },
    { name: 'Burp Suite', focus: 'Security testing' },
    { name: 'Cloud Security', focus: 'Cloud platform security' },
    { name: 'Incident Response', focus: 'Security incident management' },
  ],
};

export const projects = [
  {
    id: 'network-security',
    slug: 'network-security',
    title: 'Network Security & Troubleshooting Lab',
    category: 'Networking',
    status: 'PLANNED',
    objective: 'Build foundational network security skills through practical configuration and troubleshooting using Cisco Packet Tracer.',
    technologies: ['Cisco Packet Tracer', 'IPv4', 'IPv6', 'VLANs', 'Routing'],
    concepts: ['Network design', 'Routing protocols', 'VLAN segmentation', 'Network security', 'Troubleshooting'],
    description: 'Developing practical skills in network configuration, security concepts, and troubleshooting methodologies.',
  },
  {
    id: 'soc-monitoring',
    slug: 'soc-monitoring',
    title: 'Security Monitoring / SOC Lab',
    category: 'SOC',
    status: 'PLANNED',
    objective: 'Develop security monitoring and alert investigation capabilities through hands-on lab work.',
    technologies: ['Windows Event Logs', 'Linux Logs', 'SIEM Concepts', 'Log Analysis'],
    concepts: ['Log aggregation', 'Alert investigation', 'Threat detection', 'Security monitoring', 'Incident analysis'],
    description: 'Building expertise in security monitoring, log analysis, and SOC fundamentals.',
  },
  {
    id: 'phishing-analysis',
    slug: 'phishing-analysis',
    title: 'Phishing & Security Awareness Analysis',
    category: 'Threat Detection',
    status: 'PLANNED',
    objective: 'Analyze phishing indicators and develop security awareness through practical investigation.',
    technologies: ['Email Analysis', 'Phishing Indicators', 'Social Engineering Analysis'],
    concepts: ['Phishing indicators', 'Email security', 'Social engineering', 'User awareness', 'Defensive controls'],
    description: 'Developing skills in threat analysis and security awareness through phishing investigation.',
  },
];

export const labs = [
  {
    id: 'lab-001',
    title: 'Network Design Fundamentals',
    category: 'NETWORKING',
    status: 'PLANNED',
    objective: 'Design a basic secure network topology',
    tools: ['Cisco Packet Tracer'],
    skills: ['Network design', 'Routing', 'VLAN configuration'],
  },
  {
    id: 'lab-002',
    title: 'Log Analysis Introduction',
    category: 'SOC',
    status: 'PLANNED',
    objective: 'Analyze system logs for security events',
    tools: ['Windows Event Viewer', 'Log analysis tools'],
    skills: ['Log analysis', 'Event identification', 'Alert investigation'],
  },
  {
    id: 'lab-003',
    title: 'Phishing Email Analysis',
    category: 'THREAT DETECTION',
    status: 'PLANNED',
    objective: 'Identify phishing indicators in emails',
    tools: ['Email headers', 'URL analysis'],
    skills: ['Email analysis', 'Threat detection', 'Security awareness'],
  },
];

export const learningJourney = [
  {
    phase: 'IT Foundations',
    year: '2018-2020',
    milestone: 'National Senior Certificate (High School)',
    status: 'COMPLETED',
  },
  {
    phase: 'Technology Exploration',
    year: '2023',
    milestone: 'Cisco IoT Introduction',
    status: 'COMPLETED',
  },
  {
    phase: 'Cybersecurity Fundamentals',
    year: '2023-2026',
    milestone: 'Cisco Introduction to Cybersecurity',
    status: 'CURRENT',
  },
  {
    phase: 'Current Development',
    year: '2026',
    milestone: 'CAPACITI AI Development Programme',
    status: 'CURRENT',
  },
  {
    phase: 'Practical Labs',
    year: '2026',
    milestone: 'Network Security & SOC Labs',
    status: 'PLANNED',
  },
  {
    phase: 'Security Monitoring',
    year: '2026-2027',
    milestone: 'Hands-on SIEM and Alert Investigation',
    status: 'PLANNED',
  },
  {
    phase: 'Threat Detection',
    year: '2027',
    milestone: 'Threat Hunting and Incident Analysis',
    status: 'PLANNED',
  },
];

export const securityByDesign = [
  {
    id: 'https',
    control: 'HTTPS / TLS',
    purpose: 'Encrypt data in transit between client and server',
    status: 'IMPLEMENTED',
    explanation: 'All connections use HTTPS with modern TLS protocols.',
  },
  {
    id: 'security-headers',
    control: 'Security Headers',
    purpose: 'Protect against common web vulnerabilities',
    status: 'IMPLEMENTED',
    explanation: 'X-Content-Type-Options, X-Frame-Options, X-XSS-Protection, Referrer-Policy configured.',
  },
  {
    id: 'csp',
    control: 'Content Security Policy',
    purpose: 'Mitigate XSS and injection attacks',
    status: 'PLANNED',
    explanation: 'CSP headers will restrict resource loading to trusted sources only.',
  },
  {
    id: 'input-validation',
    control: 'Input Validation',
    purpose: 'Prevent injection attacks and malformed data',
    status: 'IMPLEMENTED',
    explanation: 'All user inputs are validated and sanitized on the client side.',
  },
  {
    id: 'dependency-management',
    control: 'Dependency Management',
    purpose: 'Minimize supply chain vulnerabilities',
    status: 'IMPLEMENTED',
    explanation: 'Only essential, well-maintained dependencies used. No unnecessary packages.',
  },
  {
    id: 'secrets-management',
    control: 'Secrets Management',
    purpose: 'Protect sensitive credentials and keys',
    status: 'IMPLEMENTED',
    explanation: 'No secrets hardcoded in source. Environment variables used where needed.',
  },
  {
    id: 'least-privilege',
    control: 'Least Privilege',
    purpose: 'Minimize exposure from compromised accounts',
    status: 'IMPLEMENTED',
    explanation: 'No sensitive personal information exposed. Only necessary details displayed.',
  },
  {
    id: 'privacy',
    control: 'Privacy & Data Protection',
    purpose: 'Protect user and candidate privacy',
    status: 'IMPLEMENTED',
    explanation: 'No tracking, no analytics, no third-party cookies. GDPR-friendly approach.',
  },
  {
    id: 'accessibility',
    control: 'Accessibility Standards',
    purpose: 'Ensure inclusive access for all users',
    status: 'IMPLEMENTED',
    explanation: 'WCAG 2.1 AA compliance: semantic HTML, keyboard navigation, screen reader support.',
  },
  {
    id: 'performance',
    control: 'Performance & DoS Mitigation',
    purpose: 'Protect against resource exhaustion attacks',
    status: 'IMPLEMENTED',
    explanation: 'Optimized assets, efficient code, minimal dependencies reduce attack surface.',
  },
];
